const L = require("./lib");
const { contents, chapter, h2, h3, p, run, bold, code, bullet,
  codeBlock, note, table, check, spacer, closing, build } = L;

const children = [
  ...contents(),

  chapter(1, "Overview"),
  p("The Documentation System is how every ID8 operating guide gets built and published. Each guide has three parts: a cover image generated from the Latent Order design system, a formatted DOCX file built from a JavaScript script using the shared lib.js library, and a page on the hub with a downloadable card. Adding documentation for a new system takes one script, one hub page, and three commands."),
  h2("When to use it"),
  bullet("You have built a new AI system or workflow and want to document it for the team."),
  bullet("An existing guide is out of date and needs a full rebuild."),
  bullet("You are adding a new section to the hub."),
  h2("What you get"),
  table(["Deliverable", "What it is", "Where it lives"], [
    ["Cover PNG", "Latent Order constellation cover, unique per guide, rendered by Chrome", "hub/static/img/cover_*.png and design/assets/"],
    ["DOCX guide", "Formatted operating guide, same editorial style across all guides", "hub/static/guides/ID8_*_Guide.docx"],
    ["Hub page", "Docusaurus page with GuideCard, content, and sidebar entry", "hub/docs/projects/*.md"],
  ], [2000, 4200, 3160]),

  chapter(2, "Building a guide"),
  p("Each guide follows the same three-step sequence: generate the cover, build the DOCX, publish the hub page. All scripts live in the design/ directory."),

  h2("Step 1. Generate the cover"),
  p([run("Open "), code("design/build_cover.js"), run(" and add an entry to the "), code("builds"), run(" array at the bottom.")]),
  ...codeBlock([
    "{ out: \"cover_my_system.html\",",
    "  seed: \"my-system-name\",",
    "  titleLines: [\"My System\", \"Name\"],",
    "  subtitle: \"One sentence describing what it does.\",",
    "  fig: \"FIG. 006 | FIELD NAME\",",
    "  plate: \"PLATE | LATENT ORDER\" },",
  ]),
  p("The seed string is the only thing that makes each constellation unique. Use a stable, lowercase, hyphenated name — changing the seed changes the constellation."),
  table(["Field", "Notes"], [
    ["seed", "Lowercase hyphenated string. Deterministic — same seed always produces the same constellation."],
    ["titleLines", "Array of 1 or 2 strings. Rendered in Roboto Serif light at 56pt. Keep each line under 18 characters."],
    ["subtitle", "One sentence, plain text, shown below the title at 15px Sora light."],
    ["fig", "Figure label shown below the header rule. Follow the FIG. 00X | FIELD NAME pattern."],
    ["plate", "Always PLATE | LATENT ORDER."],
  ], [1800, 7560]),
  p("Then run the build and render to PNG:"),
  ...codeBlock([
    "cd design",
    "node build_cover.js",
    "\"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome\" \\",
    "  --headless=new \\",
    "  --screenshot=assets/cover_my_system.png \\",
    "  --window-size=816,1056 \\",
    "  --hide-scrollbars \\",
    "  \"file://$(pwd)/cover_my_system.html\"",
    "cp assets/cover_my_system.png ../hub/static/img/cover_my_system.png",
  ]),
  note("The window size must be exactly 816x1056. That is the 8.5x11 inch document at 96 dpi. Any other size will crop or distort the cover."),

  h2("Step 2. Write the DOCX guide"),
  p([run("Create "), code("design/build_my_system.js"), run(". Require "), code("./lib"), run(" and use the primitives to build a children array, then call "), code("build()"), run(".")]),
  ...codeBlock([
    "const L = require(\"./lib\");",
    "const { contents, chapter, h2, p, bold, code, bullet,",
    "  note, table, check, codeBlock, closing, build } = L;",
    "",
    "const children = [",
    "  ...contents(),",
    "  chapter(1, \"Overview\"),",
    "  p(\"What the system does.\"),",
    "  // ... more content",
    "  ...closing(),",
    "];",
    "",
    "build(",
    "  __dirname + \"/../hub/static/guides/ID8_My_System_Guide.docx\",",
    "  \"My System\",",
    "  children,",
    "  __dirname + \"/assets/cover_my_system.png\"",
    ").then(() => console.log(\"done\"));",
  ]),
  p("Run it from the design directory:"),
  ...codeBlock(["node build_my_system.js"]),

  h2("lib.js primitives"),
  p("Every primitive returns a docx element or an array of elements. Spread arrays (codeBlock, closing, contents) with the spread operator."),
  table(["Function", "What it produces"], [
    ["chapter(num, title)", "Section heading: grey number + serif title on one line, hairline rule below. Adds to the TOC."],
    ["h2(text)", "Sub-heading in Sora bold 11pt. Adds to the TOC."],
    ["h3(text)", "Third-level heading in Sora bold 10pt, slightly muted."],
    ["p(text | runs[])", "Body paragraph. Pass a string or an array of run() / bold() / code() calls for mixed formatting."],
    ["run(text)", "Inline text run, Sora 10.5pt. Use inside p([]) for mixed content."],
    ["bold(text)", "Bold inline run."],
    ["code(text)", "Monospace inline run (Roboto Mono), 9.5pt. Use inside p([]) for filenames and commands."],
    ["bullet(text | runs[])", "Em-dash bullet item, indented."],
    ["note(text | runs[])", "Note callout: bold NOTE lead-in, no box, no fill."],
    ["table(headers[], rows[][], widths[])", "Editorial table: no vertical lines, no fills, small-caps header row with hairline, hairline separators between data rows. Widths in DXA (1440 = 1 inch). All widths must sum to 9360."],
    ["codeBlock(lines[])", "Monospace block, indented, no box. Spread with ..."],
    ["check(text | runs[])", "Checklist bullet (same style as bullet, use for pre-run checklists)."],
    ["good(text) / bad(text)", "Keep / Drop pattern. Bold lead word, plain body."],
    ["closing()", "Document closing: hairline, ID8 logo, Ambitious ideas. tagline, url. Always last. Spread with ..."],
    ["contents()", "Contents heading and TOC field. Always first after ...contents(). Spread with ..."],
  ], [2800, 6560]),
  note([run("Table widths must sum exactly to 9360 DXA (the content width at 1-inch margins on US Letter). If they do not, "), bold("build()"), run(" will still write the file but columns will be misaligned.")]),

  h2("Step 3. Publish the hub page"),
  p([run("Create "), code("hub/docs/projects/my-system.md"), run(". Follow this structure exactly.")]),
  ...codeBlock([
    "---",
    "title: My System",
    "description: One sentence for the sidebar and browser tab.",
    "---",
    "",
    "import GuideCard from '@site/src/components/GuideCard';",
    "",
    "# My System",
    "",
    "Lead paragraph — what it does, how it works, why it matters.",
    "",
    "<GuideCard",
    "  title=\"My System\"",
    "  meta=\"The formatted edition. What the guide covers.\"",
    "  cover=\"/img/cover_my_system.png\"",
    "  docx=\"/guides/ID8_My_System_Guide.docx\" />",
    "",
    "| | Detail |",
    "| --- | --- |",
    "| Row label | Row value |",
    "",
    "## Section heading",
    "",
    "Content...",
  ]),
  p([run("Then add the page to "), code("hub/sidebars.js"), run(":")]),
  ...codeBlock([
    "items: [",
    "  'projects/pitchbook-attio',",
    "  'projects/apollo-reach-out',",
    "  'projects/intelligence',",
    "  'projects/investment-memo',",
    "  'projects/my-system',   // add here",
    "],",
  ]),
  p([run("And add a row to the systems table in "), code("hub/docs/overview.md"), run(":")]),
  ...codeBlock([
    "| My System | What it does in one sentence. | Live |",
  ]),
  note("The hub runs Docusaurus. After editing any .md or .js file, the dev server hot-reloads automatically. No restart needed."),

  chapter(3, "File map"),
  table(["File", "Role"], [
    ["design/lib.js", "Core DOCX library. All shared primitives. Edit here to change the style of every guide."],
    ["design/build_cover.js", "Cover HTML generator. Add new entries to the builds array."],
    ["design/build_*.js", "One file per guide. Each imports lib.js and calls build()."],
    ["design/assets/cover_*.png", "Source cover PNGs (master copies). Always regenerate from HTML."],
    ["design/assets/fonts/", "Roboto Serif and Sora font files used by the cover renderer and lib.js."],
    ["hub/static/img/cover_*.png", "Cover PNGs served by the hub. Copied from design/assets/ after generation."],
    ["hub/static/guides/ID8_*_Guide.docx", "DOCX files served by the hub. Written directly by build_*.js."],
    ["hub/docs/projects/*.md", "One Docusaurus page per project."],
    ["hub/sidebars.js", "Sidebar nav config. Add new project pages here."],
    ["hub/docs/overview.md", "AI Capabilities overview page and systems table."],
  ], [3600, 5760]),

  chapter(4, "Reference"),
  h2("Adding a new guide — checklist"),
  check([run("Entry added to "), code("design/build_cover.js"), run(" builds array with unique seed and fig number")]),
  check([run("Cover HTML generated: "), code("node build_cover.js")]),
  check("Cover PNG rendered via Chrome headless at 816x1056"),
  check([run("Cover PNG copied to "), code("hub/static/img/cover_my_system.png")]),
  check([run("DOCX script written at "), code("design/build_my_system.js"), run(" using lib.js primitives")]),
  check("DOCX built and written to hub/static/guides/"),
  check([run("Hub page created at "), code("hub/docs/projects/my-system.md"), run(" with GuideCard")]),
  check([run("Page added to "), code("hub/sidebars.js")]),
  check([run("Row added to systems table in "), code("hub/docs/overview.md")]),
  check("Hub dev server checked — page renders, GuideCard shows, DOCX downloads"),

  h2("Cover fig number sequence"),
  table(["Fig", "Guide"], [
    ["FIG. 001", "Canvas (ID8 brand plate — not a guide)"],
    ["FIG. 002", "Apollo Reach Out"],
    ["FIG. 003", "PitchBook → Attio Pipeline"],
    ["FIG. 004", "Investment Memo Generator"],
    ["FIG. 005", "Documentation System"],
    ["FIG. 006+", "Next guide — increment by one"],
  ], [2000, 7360]),

  h2("Table width reference"),
  p("All table widths must sum to 9360 DXA. Common column splits:"),
  table(["Split", "Column widths"], [
    ["2 col, 25/75", "2400 + 6960"],
    ["2 col, 30/70", "2800 + 6560"],
    ["2 col, 35/65", "3200 + 6160"],
    ["2 col, 40/60", "3760 + 5600"],
    ["2 col, 45/55", "4200 + 5160"],
    ["3 col, num + 30/65", "360 + 2800 + 6200"],
    ["3 col, equal thirds", "3120 + 3120 + 3120"],
  ], [2800, 6560]),
  note("DXA units: 1440 DXA = 1 inch. Content width at 1-inch margins on US Letter = 9360 DXA (6.5 inches)."),

  ...closing(),
];

build(
  __dirname + "/../hub/static/guides/ID8_Documentation_System_Guide.docx",
  "Documentation System",
  children,
  __dirname + "/assets/cover_hub_docs.png"
).then(() => console.log("Documentation System guide written."));
