const L = require("./lib");
const { contents, chapter, h2, h3, p, run, bold, code, bullet, num,
  codeBlock, note, table, good, bad, check, spacer, closing, build } = L;

const children = [
  ...contents(),

  chapter(1, "Overview"),
  p("Apollo Reach Out turns Apollo's contact database into a short, clean list of real family office and RIA decision-makers. It enriches each one and loads them into a managed outbound sequence."),
  p("The hard part is filtering. A broad search for financial services in Los Angeles returns about 61,889 people. That is every banker, broker, and fintech employee in the city. This guide is the recipe that gets you down to 50 to 300 real prospects."),
  h2("When to use it"),
  bullet("You are preparing an outbound push for a city or an event, like the LA trip."),
  bullet("You need a fresh list of prospects to feed the LP screener."),
  bullet("You want to load qualified contacts into a sequence without touching anyone already in a live campaign."),
  h2("What you get"),
  table(["Stage", "Output"], [
    ["Filtered search", "50 to 300 clean FO and RIA decision-makers in the target city"],
    ["Enrichment", "Research and a 0 to 100 LP fit score per firm"],
    ["Sequence load", "Contacts mirrored into Apollo and enrolled in the managed sequence"],
  ], [2400, 6960]),
  note("Quality beats quantity here. A hundred precise contacts outperform five thousand broad ones. If loosening a filter grows the list, the list usually got worse."),

  chapter(2, "Building the target list"),
  p("Set the filters in this order. Each layer removes a category of bad results. The employee count filter in step 3 does most of the work on its own."),
  h2("Step 1. Company keywords to include"),
  p("Set the keyword type to ANY so a contact matches on any single term. Use only the terms real family offices use about themselves. Large asset managers never call themselves a family office."),
  bullet("family office"),
  bullet("single family office"),
  bullet("multi-family office"),
  bullet("private family office"),
  bullet("family wealth"),
  bullet("private wealth"),
  note([run("Skip the broad terms "), bold("wealth management"), run(", "), bold("investment management"), run(", and "), bold("financial services"), run(". They pull in large platforms like Mercer, Edward Jones, and Raymond James.")]),
  h2("Step 2. Company keywords to exclude"),
  p("Exclusions do more work than inclusions. Paste these into the exclude box."),
  table(["Category", "Exclude terms"], [
    ["Banks and wirehouses", "bank, banking, brokerage, broker dealer, Raymond James, Edward Jones, Morgan Stanley, Wells Fargo, Merrill Lynch, UBS, Charles Schwab, Ameriprise, LPL Financial"],
    ["Large platforms", "Fidelity, Vanguard, BlackRock, asset management, fund administration"],
    ["Insurance", "insurance, Northwestern Mutual"],
    ["Wrong asset class", "hedge fund, private equity, venture capital, real estate"],
    ["Wrong kind of finance", "accounting, tax, payroll"],
    ["Tech in finance", "fintech, software, technology"],
  ], [2600, 6760]),
  h2("Step 3. Employee count"),
  p("Real family offices have 2 to 30 employees. Platforms have hundreds or thousands. Under Company Headcount, select 1 to 10 and 11 to 50."),
  note("This one filter removes about 90 percent of the wrong results. If you do nothing else, do this."),
  h2("Step 4. Job titles"),
  p("Under Job Title, add the decision-maker titles."),
  bullet("Partner, Managing Partner, Principal"),
  bullet("Chief Investment Officer, Head of Investments, Director of Investments"),
  bullet("Managing Director, Investment Director, Portfolio Manager"),
  h2("Step 5. Seniority"),
  p("Under Seniority, select Owner or Partner, C-Suite, VP, and Director."),
  h2("Step 6. Location"),
  p("Keep the geography tight to the campaign. For the current effort this is Los Angeles."),
  h2("RIA sub-search"),
  p("RIAs that serve high-net-worth clients are small firms. Run them as a separate search."),
  table(["Filter", "Value"], [
    ["Keywords", "registered investment advisor OR RIA"],
    ["Headcount", "1 to 50"],
    ["Titles", "Partner, CIO, Managing Director, Principal"],
  ], [2400, 6960]),
  p("Any RIA with 500 or more employees is a retail platform, not what you want."),
  h2("What good looks like"),
  p("After all layers you should land between 50 and 300 results."),
  good("Unfamiliar, generic names like Westlake Capital or Meridian Family Office."),
  bad("Names you recognize. If you know the firm, it is too big."),

  chapter(3, "Enrich and launch"),
  h2("Enrich with Perplexity"),
  p("Research each firm before you reach out. The enrichment step scores each firm against the ID8 Growth Opportunities Fund I rubric."),
  table(["Script", "Role"], [
    ["perplexity_lp_screener.py", "Per-firm web research and structured notes"],
    ["lp_screener_hybrid.py", "Applies the 0 to 100 rubric and tiers firms"],
  ], [3200, 6160]),
  p([run("These also back the "), bold("lp-prospect-screener"), run(" skill. Hand it a CSV of contacts and it returns a scored, tiered CSV.")]),
  note("Screen before you load the sequence. Enroll only Tier 1 and Tier 2 firms."),
  h2("Load the sequence"),
  p("The sync mirrors your Attio People into Apollo and parks them in a dormant holding sequence. Any later Apollo search then flags those people as already sequenced, so you never double-touch a contact."),
  p([run("It lives in "), code("attio_apollo_sync.py"), run(" and runs from "), code("/sync-apollo"), run(", with "), code("/sync-apollo/status"), run(" for progress.")]),
  ...codeBlock([
    "curl -X POST https://<your-app>/sync-apollo",
    "curl https://<your-app>/sync-apollo/status",
  ]),
  h2("Configuration"),
  table(["Env var", "Notes"], [
    ["APOLLO_API_KEY", "Must be a master key. add_contact_ids returns 403 otherwise"],
    ["APOLLO_HOLDING_SEQUENCE_ID", "A dormant sequence with no active email steps"],
    ["APOLLO_MAILBOX_ID", "Optional mailbox for the sequence"],
  ], [3400, 5960]),
  h2("API gotchas"),
  p("These fail silently with no error, so they are easy to miss."),
  bullet([code("add_contact_ids"), run(" needs a master API key.")]),
  bullet([run("Sequence flags are snake_case: "), code("sequence_active_in_other_campaigns"), run(" and "), code("sequence_finished_in_other_campaigns"), run(". CamelCase is ignored. Keep both false so live contacts stay put.")]),
  bullet([run("The mailbox param is "), code("send_email_from_email_account_id"), run(", and "), code("emailer_campaign_id"), run(" must echo the sequence id.")]),
  bullet([run("Upsert with "), code("POST /contacts"), run(" and "), code("run_dedupe=true"), run(". The lookup fallback is "), code("POST /contacts/search"), run(".")]),
  bullet("Contact search cannot filter by sequence membership. Re-running is safe because Apollo dedupes and a contact can only sit in a sequence once."),

  chapter(4, "Reference"),
  h3("Include keywords, type ANY"),
  ...codeBlock(["family office, single family office, multi-family office,", "private family office, family wealth, private wealth"]),
  h3("Exclude keywords"),
  ...codeBlock([
    "bank, banking, brokerage, broker dealer, insurance,",
    "asset management, fund administration, hedge fund,",
    "private equity, venture capital, real estate, accounting,",
    "tax, payroll, fintech, software, technology, Raymond James,",
    "Edward Jones, Morgan Stanley, Wells Fargo, Merrill Lynch, UBS,",
    "Fidelity, Vanguard, BlackRock, Charles Schwab, Ameriprise,",
    "Northwestern Mutual, LPL Financial",
  ]),
  h3("Other layers"),
  table(["Filter", "Value"], [
    ["Employee count", "1 to 10 and 11 to 50"],
    ["Titles", "Partner, Managing Partner, CIO, Managing Director, Head of Investments, Director of Investments, Portfolio Manager, Principal, Investment Director"],
    ["Seniority", "Owner or Partner, C-Suite, VP, Director"],
    ["Location", "Los Angeles for the current campaign"],
  ], [2400, 6960]),
  h2("Checklist"),
  check("Include keywords set to ANY, only self-descriptive family office terms"),
  check("Exclude list pasted in full"),
  check("Headcount limited to 1 to 10 and 11 to 50"),
  check("Decision-maker titles and seniority added"),
  check("Location tight to the campaign"),
  check("Result is 50 to 300 and full of unfamiliar firm names"),
  check("Screened, kept Tier 1 and Tier 2, then ran /sync-apollo"),
  h2("Troubleshooting"),
  h3("Search returns big recognizable firms"),
  p("Your include keywords are too broad or the headcount filter is off. Remove wealth and investment management, confirm headcount 1 to 10 and 11 to 50, and add the exclude list."),
  h3("Sequence enroll seems to do nothing"),
  p("Usually camelCase sequence flags, which Apollo ignores, or a non-master API key. Use snake_case flags and a master key."),
  h3("Contacts come through blank for title, LinkedIn, or phone"),
  p([run("The People slugs in "), code("extract_contact"), run(" are best guesses. Confirm them against the live Attio People object if those fields are empty.")]),

  ...closing(),
];

build(__dirname + "/../hub/static/guides/ID8_Apollo_Reach_Out_Guide.docx", "Apollo Reach Out", children, __dirname + "/assets/cover_apollo.png")
  .then(() => console.log("Apollo guide written."));
