const L = require("./lib");
const { contents, chapter, h2, h3, p, run, bold, code, bullet, num,
  codeBlock, note, table, good, bad, check, spacer, closing, build } = L;

const children = [
  ...contents(),

  chapter(1, "Overview"),
  p("The Investment Memo Generator turns raw deal data into a complete ID8 investment memo — formatted as a DOCX file in the canonical style. It runs a 16-agent workflow that handles intake, research gap-filling, parallel section writing, and editorial assembly. The output reads like the Polymarket, Saronic, and Hadrian memos the format was derived from."),
  p("Runtime is 15 to 20 minutes. The workflow consumes roughly 500k tokens across its 16 agents. Plan accordingly before running on a deal."),
  h2("When to use it"),
  bullet("A deal has cleared the preliminary fit filter and you want a full memo before IC."),
  bullet("You are co-investing and need a fast, rigorous memo anchored to the lead investor's thesis."),
  bullet("You want to pressure-test your own analysis against an independently assembled section set."),
  h2("What you get"),
  table(["Phase", "What happens"], [
    ["Intake", "One agent digests all raw input — your documents, PitchBook data, and web research — into a structured company brief. Data gaps flagged as DATA GAP:. Conflicts flagged as CONFLICT: user says X, external says Y."],
    ["Brief", "The structured brief is packaged into 14 section-specific data blocks, each containing only the facts relevant to that section."],
    ["Write", "14 agents run in parallel, each writing one section from its brief. Institutional voice, no hedging, every paragraph anchored to a figure or named entity."],
    ["Edit", "One editorial agent assembles all 14 sections, adds cross-references, verifies consistency, and finalizes the complete memo."],
    ["Output", ".docx file, roughly 4,000 to 7,000 words, ID8 canonical typography and table styles."],
  ], [2000, 7360]),
  note("The workflow costs around 500k tokens and takes 15 to 20 minutes. Do not run it on a deal that has not cleared initial review."),

  chapter(2, "Running it"),
  p([run("Type "), bold("/investment-memo"), run(" in Claude Code. Before the workflow runs, you will be asked for any missing inputs. The minimum required is a company name, deal type, and basic round terms. Everything else is sourced automatically from PitchBook and the web.")]),
  h2("Fastest path"),
  p("Provide the company name and deal description. The intake agent fills the rest from PitchBook and web search."),
  h2("Richest output"),
  p("Attach a pitch deck, term sheet, and financial model before running. The agents prioritize your documents over external sources and flag any conflicts. Each document you attach removes data gaps and sharpens the section that uses it."),
  h2("What to provide"),
  table(["Input", "Notes"], [
    ["Company name", "Required."],
    ["One-line description", "Optional. Intake agent drafts one if missing."],
    ["Deal type", "e.g. Series D — Preferred Stock, Founder Secondary — Common Stock"],
    ["Round terms", "Security type, round size, pre-money, post-money, lead investor, prior round"],
    ["Memo date", "e.g. June 2026"],
    ["Attached documents", "Pitch deck, financial model, term sheet — all optional but each adds depth and removes gaps"],
  ], [2600, 6760]),
  note("If your data conflicts with what PitchBook or web search returns — e.g. a different valuation — Claude surfaces the conflict before running and uses your figure unless you say otherwise."),
  h2("What happens during the run"),
  p("The four phases run sequentially. During Write, you will see 14 agents fire in parallel in the workflow progress view. The Edit agent runs last and takes the longest single step — it reads all 14 sections before assembling the final document."),
  bullet("Intake: 1 to 3 minutes"),
  bullet("Brief: under 1 minute"),
  bullet("Write: 8 to 12 minutes (14 agents in parallel)"),
  bullet("Edit: 3 to 5 minutes"),

  chapter(3, "The output"),
  p("The output is a .docx file saved to Downloads by default. You can specify a different path when prompted at the end of the run."),
  h2("The 14 sections"),
  table(["#", "Section", "What it covers"], [
    ["1", "Investment Overview", "Executive summary — thesis bullets, key risks, conviction statement. A reader who only reads this section understands the full thesis."],
    ["2", "Investment Highlights", "4 to 5 named thesis pillars, each a bold H2 followed by 2 to 3 quantified prose paragraphs. No bullets — all analytical narrative."],
    ["3", "Business Overview", "What the company builds, sells, and operates. Product table for hardware or multi-product. What Trades table for marketplaces."],
    ["4", "Revenue Model", "One H2 per revenue stream: mechanism, current scale, and projected unit economics."],
    ["5", "Addressable Market", "TAM methodology, why the market is expanding now, company's current penetration vs. TAM."],
    ["6", "Founder & Management Team", "One H2 per founder or key exec: prior companies, exits, domain credentials. Advisory board if notable."],
    ["7", "Raise Timeline", "Full funding history table: Round — Date — Size — Post-Money — Lead Investor(s)."],
    ["8", "Competitor Overview", "Competitive landscape narrative plus 4 to 7 row competitor matrix with threat level and rationale per competitor."],
    ["9", "Lead Investor", "Strategic profile, fund performance table, and a section on why this lead chose this company."],
    ["10", "Financial Snapshot", "Key metrics table: revenue, growth, gross margin, EBITDA, valuation, revenue multiple. Footnoted source and date."],
    ["11", "Valuation", "Comps table (5 to 8 private and public peers), entry multiple analysis, path to multiple re-rate, optional scenario analysis."],
    ["12", "Exit & Monetization", "IPO path, strategic acquisition (named buyer universe), secondary liquidity. Bear, Base, Bull exit scenario table."],
    ["13", "Risk Factors", "5 to 6 named risks. Each: 2 to 4 sentence problem citing specific entities, then a mitigant bullet 3 to 5x longer naming partners, dates, and programs."],
    ["14", "Key Investment Assumptions", "5 to 7 numbered, falsifiable assumptions the thesis depends on — specific enough to monitor as the deal ages."],
  ], [360, 2640, 6360]),
  h2("Format and style"),
  p("The DOCX file is built to the ID8 canonical style, matching the typography and table formatting of the reference memos."),
  table(["Element", "Style"], [
    ["Section headings", "Roboto Serif 16pt bold, bottom border rule"],
    ["Body text", "Sora 11pt justified, #1a1a1a"],
    ["Table headers", "Sora 9pt all-caps with hairline rule, no fill"],
    ["Table rows", "Sora 9pt, hairline separator between rows, no fill"],
    ["Exit scenario rows", "Bear row amber, Bull row green"],
    ["Footer", "Page number centered, no header"],
  ], [3000, 6360]),
  h2("Writing voice"),
  p("Every section is written in the same institutional style. The editorial agent enforces this across the assembled document."),
  bullet([bold("Declarative and third-person."), run(" No first-person. No hedging in body text — hedging belongs only in footnotes.")]),
  bullet([bold("Quantitatively dense."), run(" Every paragraph contains at least one specific dollar figure, percentage, date, or named entity.")]),
  bullet([bold("No superlatives."), run(" Precise comparative framing: the only company that simultaneously holds X, Y, and Z — not the best.")]),
  bullet([bold("Cross-references explicit."), run(" Sections refer to each other: discussed in detail in the Risk Factors section.")]),
  bullet([bold("Data attributed."), run(" Figures cite their source: per PitchBook, per management, per Bloomberg.")]),

  chapter(4, "Reference"),
  h2("Pre-run checklist"),
  check("Company name and deal description ready"),
  check("Round terms available: size, pre-money, lead investor, prior round"),
  check("Pitch deck, term sheet, or financials attached if you have them"),
  check("Deal has cleared initial review — 500k tokens and 15 to 20 minutes"),
  check([run("Type "), bold("/investment-memo"), run(" in Claude Code and follow the prompts")]),
  check("Confirm or correct any data conflicts surfaced before the workflow starts"),
  check("Note the output path when the file saves"),
  h2("Data gap behavior"),
  p([run("When the intake agent cannot find data for a required field, it writes a "), code("DATA GAP:"), run(" placeholder. It will not invent figures. If a section has too many gaps to write substantively, it is flagged for manual review in the final report. Add more source documents or fill the placeholder after generation.")]),
  h2("Troubleshooting"),
  h3("Workflow stalls or times out"),
  p([run("Re-run "), bold("/investment-memo"), run(". The workflow is resumable — completed agents return cached results and only the remaining phases re-run.")]),
  h3("Valuation or round size is wrong"),
  p("Provide the correct figure in your initial input. Claude surfaces conflicts before running — confirm your number at that point. Your figure always wins."),
  h3("Section has many DATA GAP: flags"),
  p("Add more source documents before running, or manually fill the placeholder after generation. PitchBook data is the most common gap source for early-stage companies."),
  h3("DOCX formatting looks wrong in Google Docs"),
  p("Open in Microsoft Word. Advanced DOCX formatting — table border rules, paragraph borders — is not fully supported in Google Docs."),
  h3("PitchBook data is outdated"),
  p("Add the current data as text in your initial prompt. Your input always overrides external sources."),
  h2("Technical files"),
  table(["File", "Role"], [
    [".claude/skills/investment-memo/scripts/workflow.js", "Workflow orchestration — 4 phases, 16 agents"],
    [".claude/skills/investment-memo/scripts/build_memo.py", "DOCX builder — converts JSON output to formatted Word file"],
    [".claude/skills/investment-memo/references/style-guide.md", "Typography, color palette, table system, writing voice"],
    [".claude/skills/investment-memo/references/section-guide.md", "Per-section structure, length targets, analytical depth"],
  ], [4400, 4960]),

  ...closing(),
];

build(
  __dirname + "/../hub/static/guides/ID8_Investment_Memo_Generator_Guide.docx",
  "Investment Memo Generator",
  children,
  __dirname + "/assets/cover_investment_memo.png"
).then(() => console.log("Investment Memo Generator guide written."));
