const L = require("./lib");
const { contents, chapter, h2, h3, p, run, bold, code, bullet, num,
  codeBlock, note, table, good, bad, check, spacer, closing, build } = L;

const children = [
  ...contents(),

  chapter(1, "Overview"),
  p("This pipeline reads PitchBook exports of deals, companies, and investors and writes them into ID8's Attio CRM. It creates and updates Deal and Company records, stages deals, and links each deal to the VC firms that invested so the investor graph in Attio stays accurate."),
  table(["", "Detail"], [
    ["Input", "A PitchBook CSV of deals and companies, ideally with the Investors Websites column"],
    ["Output", "Attio Deals and Companies, staged, with lead, new, and all-investor links"],
    ["Code", "attio_apollo_sync.py, app.py, attio_import/"],
  ], [1800, 7560]),
  note([run("The most important column in your export is "), bold("Investors Websites"), run(". Without it, only VCs that already exist in Attio by name get linked. Everything else is skipped. See chapter 3.")]),

  chapter(2, "How it works"),
  h2("The flow"),
  num("Export deals and companies from PitchBook, including the Investors Websites column."),
  num("Run the processing endpoint. Records are matched or created in Attio."),
  num("Deal stage is applied per the staging rules below."),
  num("Investor references are resolved and written as record links."),
  h2("Write values are not read values"),
  p("Attio's write format for a value differs from its read format. Writing the read shape fails silently. The field just does not get set, with no error. This is the most common reason a field looks like it did not update."),
  table(["Type", "Write format"], [
    ["select, single", "plain string of the option title, like \"slug\": \"Yes\". Not [{\"option\":\"Yes\"}]"],
    ["multi-select", "array of title strings, like \"slug\": [\"A\", \"B\"]"],
    ["text", "[{\"value\": \"...\"}]"],
    ["number", "[{\"value\": 123}]"],
    ["currency", "[{\"currency_value\": 123}]. Money in millions, so multiply by 1,000,000"],
    ["date", "[{\"value\": \"YYYY-MM-DD\"}]"],
    ["status", "[{\"status\": \"Watchlist\"}]"],
    ["record reference", "[{\"target_object\": \"companies\", \"target_record_id\": \"...\"}]"],
  ], [2200, 7160]),
  note([run("A single-select must be a plain string. The "), code("[{\"option\": \"Yes\"}]"), run(" shape is the read format and is ignored on write. This is why "), code("top_10_vc"), run(" used to not get set. An unknown option errors, so "), code("ensure_select_option"), run(" creates it first.")]),

  chapter(3, "Investor linking"),
  h2("The three investor slugs"),
  p("The Deals object links VC firms to Company records through reference attributes. The link slugs, confirmed in the Attio UI and held in INVESTOR_REF_MAP, are below."),
  table(["Category", "Reference slug"], [
    ["Lead investors", "lead_investors_8"],
    ["New investors", "new_investors_5"],
    ["All investors, including follow-ons", "investors_5"],
  ], [4200, 5160]),
  note([run("These are different from the text slugs in FIELD_MAP, which are "), code("lead_investors"), run(", "), code("new_investors_7"), run(", and "), code("investors"), run(". Those drive email and display. The slugs above create the actual links.")]),
  h2("Domain versus record ID"),
  p("These are two different mechanisms depending on whether you use the CSV importer or the API."),
  h3("CSV importer links by domain"),
  bullet([run("Put the company domain in the cell and match on Domains. Record-ID matching does not work reliably in the importer.")]),
  bullet([run("Separate multi-value cells with a comma and a space, not a semicolon.")]),
  h3("The API links by target_record_id"),
  bullet([run("In an API write, references must be "), code("target_record_id"), run(". There is no link-by-domain in the API.")]),
  bullet([run("resolve_investor_links matches by domain first, then by name, then sends the resolved id. Do not change it to emit a domain or the call breaks.")]),
  h2("Create if website"),
  p("resolve_investor_links matches by domain first, then name. If an investor is unmatched and the export gave its domain, it creates the company and caches the new id so repeats reuse it. Unmatched with no domain gets skipped, since you cannot create a company without a domain."),
  note([run("To link or create every investor on a deal, the export must include the "), bold("Investors Websites"), run(" column. A names-only export only links VCs that already exist by name. Search-result exports often drop this column, which is why NinjaOne once showed 1 of 12 investors linked.")]),

  chapter(4, "Backfill, staging, and fixes"),
  h2("Bulk backfill, use CSV not the API"),
  p("get_company_index with refresh pages every Company. On a large workspace that alone passes the 30 second gunicorn timeout, so /process, /backfill-investors, and /update-investors all return 500. A single-row request to /update-investors once took 30.7 seconds and failed."),
  p("For a one-off backfill, do not fight the timeout. Build a CSV locally and import it to Deals in the Attio UI."),
  num([run("One row per deal, with domain columns per category, multi-value separated by a comma and a space. pandas quotes the cells for you.")]),
  num([run("Reuse "), code("parse_investor_websites"), run(" for the name-to-domain map and "), code("parse_investors"), run(" per category.")]),
  num([run("Import to Deals: match deals by Name, map domain columns to "), code("lead_investors_8"), run(", "), code("new_investors_5"), run(", and "), code("investors_5"), run(", match target Companies on Domains, and create missing ones.")]),
  note("Duplicate deal names across Series make name-matching ambiguous. Handle those by Series or by hand. app.py has a threaded /update-investors route for the API path, but it needs a redeploy and the CSV route is the one that works."),
  h2("Staging rules"),
  p([code("/process-top10"), run(" puts only new deals on Radar. Existing deals keep their current stage, so do not auto-promote a Qualified deal.")]),
  p([run("To bulk-promote existing Qualified deals to Radar, use "), code("/fix-radar-stages"), run(". It moves Qualified deals that have "), code("new_investors_7"), run(".")]),
  h2("Troubleshooting"),
  h3("A field will not set and there is no error"),
  p("Almost always the write versus read format. Check the table in chapter 2, especially single-selects."),
  h3("Only some investors linked on a deal"),
  p("The export is missing the Investors Websites column, so unmatched investors with no domain were skipped. Re-export with that column."),
  h3("An endpoint returns 500 on a large workspace"),
  p("The company index refresh passed the 30 second timeout. Use the CSV backfill instead."),

  chapter(5, "Reference"),
  h3("Link slugs, INVESTOR_REF_MAP"),
  table(["Category", "Slug"], [
    ["Lead investors", "lead_investors_8"],
    ["New investors", "new_investors_5"],
    ["All investors", "investors_5"],
  ], [4200, 5160]),
  h3("Text slugs, FIELD_MAP"),
  table(["Category", "Slug"], [
    ["Lead investors text", "lead_investors"],
    ["New investors text", "new_investors_7"],
    ["All investors text", "investors"],
  ], [4200, 5160]),
  h2("Checklist"),
  check("Export includes the Investors Websites column"),
  check("Multi-value investor cells separated by a comma and a space"),
  check("Duplicate Series deal names handled separately"),
  check("Single-selects written as plain strings"),
  check("Currency in millions multiplied by 1,000,000"),
  check("References use target_record_id for the API or domain for the importer"),
  check("Spot-checked a deal for all expected investor links"),
  check("New deals on Radar, existing deals kept their stage"),

  ...closing(),
];

build(__dirname + "/../hub/static/guides/ID8_PitchBook_Attio_Pipeline_Guide.docx", "PitchBook to Attio Pipeline", children, __dirname + "/assets/cover_pitchbook.png")
  .then(() => console.log("PitchBook guide written."));
