import 'server-only';
import { db, isoDate } from './firestore';

// One doc per email, keyed by the lowercased address itself (not an
// autogenerated id) so lookups during sign-in are a single get(), not a query.
const COLLECTION = 'investorAccess';

export async function getOrCreateAccessRecord(email, name) {
  const ref = db().collection(COLLECTION).doc(email);
  const doc = await ref.get();
  if (doc.exists) return doc.data();
  const record = { email, name: name || null, status: 'pending', requestedAt: new Date() };
  await ref.set(record);
  return record;
}

export async function listAccessRequests() {
  const snap = await db().collection(COLLECTION).orderBy('requestedAt', 'desc').get();
  return snap.docs.map((doc) => {
    const d = doc.data();
    return {
      email: doc.id,
      name: d.name || null,
      status: d.status,
      requestedAt: isoDate(d.requestedAt),
      decidedAt: isoDate(d.decidedAt),
    };
  });
}

export async function setAccessStatus(email, status) {
  await db().collection(COLLECTION).doc(email).set({ status, decidedAt: new Date() }, { merge: true });
}
