/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [
    { type: 'doc', id: 'overview', label: 'Capabilities' },
    {
      type: 'category',
      label: 'Projects',
      collapsed: false,
      items: [
        'projects/pitchbook-attio',
        'projects/apollo-reach-out',
        'projects/intelligence',
        'projects/investment-memo',
        'projects/hub-docs',
      ],
    },
    {
      type: 'category',
      label: 'Research',
      collapsed: false,
      link: { type: 'doc', id: 'research/index' },
      items: [
        {
          type: 'category',
          label: 'Companies',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'research/companies' }],
        },
        'research/market-map',
      ],
    },
    { type: 'doc', id: 'admin/index', label: 'Admin' },
  ],
};

module.exports = sidebars;
